version: '3.8'

services:
  # Next.js Frontend (Development)
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-frontend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    command: npm run dev

  # Django API Server (Development)
  django-api:
    # Replace with your Django development configuration
    image: nginx:alpine
    container_name: django-api-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/django.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
