version: '3.8'

services:
  # Next.js Frontend
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network
    depends_on:
      - nginx

  # Django API Server (assuming it exists)
  django-api:
    # Uncomment and configure this section if you have a Django API
    # build:
    #   context: ../your-django-project
    #   dockerfile: Dockerfile
    # container_name: django-api
    # restart: unless-stopped
    # environment:
    #   - DEBUG=False
    #   - ALLOWED_HOSTS=localhost,127.0.0.1,django-api
    # networks:
    #   - app-network
    # ports:
    #   - "8000:8000"
    image: nginx:alpine
    container_name: django-api-placeholder
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8000:80"
    volumes:
      - ./nginx/django.conf:/etc/nginx/conf.d/default.conf

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network
    depends_on:
      - nextjs-app

networks:
  app-network:
    driver: bridge

volumes:
  nginx-ssl:
