import { Geist, Geist_Mono, Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";
const notoKufi = Noto_Kufi_Arabic({
    subsets: ["arabic"],
    weight: ["400", "500", "600", "700"], // choose weights you need
    variable: "--font-noto-kufi",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir={`rtl`}>
      <body
        className={`${notoKufi.variable} ${notoKufi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
